version: '3.8'

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: proveedores_db
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  php:
    build: .
    container_name: symfony_app
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    command: >
      bash -c "apt update && apt install -y unzip zip && curl -sS https://getcomposer.org/installer | php && mv composer.phar /usr/local/bin/composer && composer install && php -S 0.0.0.0:8000 -t public"

volumes:
  mysql_data:
